수동입력 사이즈 추천 및 관련 오류
OWN-SIZE/onsize-extension pull request #45
Opened 2023-02-23 12:12 UTC by ilmerry

## 이슈 넘버
- close #32 

## 구현 사항

- [ ] 수동입력 사이즈 추천
- [ ] 수동입력 관련 각종 오류들

## Need Review
- 수동입력 한줄 입력시 recoil state `productSelfWriteState`를 저장해서 그 값을 비교뷰에 전달합니다
- 수동입력 두줄 입력시 기존에 있던 사이즈 추천 api를 사용해 요소 두개짜리 배열을 post합니다
- 이를 위해 useSizeRecommend 훅을 참고하여 `useSizeCompare` 커스텀 훅을 만들었습니다. 차이점은 TopOrBottom 값이 아니라 서버에 보낼 사이즈 값 body를 인자로 받아서 처리합니다.
```ts
const executeSizeRecommmend = async (body: PostSizeTableInput, url: string) => {
    setCurrentView('loading');

    await sizeCrawling(body);
    await getSizeRecommendResult(topOrBottom === 'top' ? body.sizes[0].topItemId : body.sizes[0].bottomItemId, url);

    setTimeout(async () => {
      renderNextView();
    }, 100);
  };
```

2023-02-24 02:32 UTC, leeseooo requested changes
size type을 조금 수정해야해😅

지금 타입이 이렇게 되어있을텐데 `SizeType`에서 `TopType | null` 이 아니라 `TopType`으로만 고쳐야하고, `TopType` 안에서 각 프로퍼티들에게 null을 허용해줘야돼
topLength: number | null; 이런식으로!
이 부분도 수정해서 반영해주라 그리고 타입 에러 잘 모르겠으면 같이 논의하면서 해결해보자!
```ts
// 기존 코드
export interface TopType {
  topLength: number;
  shoulder: number;
  chest: number;
  isWidthOfTop: boolean;
}
export interface BottomType {
  bottomLength: number;
  rise: number;
  waist: number;
  thigh: number;
  hem: number;
  isWidthOfBottom: boolean;
}

export interface SizeType {
  top: TopType | null;
  bottom: BottomType | null;
}
```

2023-02-24 02:32 UTC, leeseooo commented on src/hooks/queries/useSizeCompare.ts
> +    }, 100);
http 요청하는 동안만 로딩 로티 뜨도록 수정해서 setTimeout 걸어주는 부분은 제거해주라!
그냥 바로 renderNextView() 호출해주면 되고 renderNextView 내부에서도 setTimeout 없애주라

2023-02-24 02:32 UTC, leeseooo commented on src/hooks/queries/useSizeCompare.ts
> +    // }
요거는 불필요하면 삭제해주면 되겠다

2023-02-24 02:32 UTC, leeseooo commented on src/pages/Popup/size-write/index.tsx
> +          //manualInputNum: 0,
이거 삭제된 프로퍼티라 지워도 돼

2023-02-24 02:32 UTC, leeseooo commented on src/pages/Popup/size-write/index.tsx
> +        };
key,value 같으면 value 생략해도돼

2023-02-24 02:32 UTC, leeseooo commented on src/pages/Popup/size-write/index.tsx
> +        sizes.push(addedInput);
한 줄로 써도 될듯!

2023-02-24 02:32 UTC, leeseooo commented on src/components/size-compare/Sizes.tsx
>    isSelfWrite?: boolean;
이거 productSizes 넣으면 다른 뷰에서 에러나서 optional로 줘야할듯?
근데 productSelfWriteState 만들어서 atom에 저장해두는 것 같던데 이렇게 props로 받지 말고 useRecoilState로 import해서 쓰는건 어때?🤔
Sizes를 최대한 의존성 안걸리게 쓰는게 좋을 것 같아 SelfWriteCompare랑 Compare에서 둘다 쓰고 있거든

2023-02-24 08:06 UTC, ilmerry commented on src/components/size-compare/Sizes.tsx
>    isSelfWrite?: boolean;
atom은 SizeTableType이라서 TODO에 적힌대로 초기값을 전달하기 위해 쓴 state고, 그걸 SizePropType으로 변환해서 props로 전달하게끔 한거거든.. 최대한 안건드리려고 이렇게 한거였어
```tsx
/** TODO : 수동입력 시 그 입력한 값을 여기에 저장 */
  const [productSize, setProductSize] = useState<SizeType>({
    top: {
      topLength: productSelfWrite.topLength ?? 0,
      chest: productSelfWrite.chest ?? 0,
      shoulder: productSelfWrite.shoulder ?? 0,
      isWidthOfTop: productSelfWrite.isWidthOfTop,
    },
    bottom: {
      bottomLength: productSelfWrite.bottomLength ?? 0,
      waist: productSelfWrite.waist ?? 0,
      thigh: productSelfWrite.thigh ?? 0,
      rise: productSelfWrite.rise ?? 0,
      hem: productSelfWrite.hem ?? 0,
      isWidthOfBottom: productSelfWrite.isWidthOfBottom,
    },
  });
```

2023-02-24 08:08 UTC, ilmerry commented on src/components/size-compare/Sizes.tsx
>    isSelfWrite?: boolean;
그리고 size랑 productSize는 둘다 반드시 들어와야하지 않아?? 그래야 내 사이즈랑 비교가 가능하다고 생각했어

2023-02-24 08:10 UTC, ilmerry commented on src/components/size-compare/Sizes.tsx
>    isSelfWrite?: boolean;
아 Sizes에서만 option처리 해주면 되는구나!

2023-02-24 08:12 UTC, ilmerry commented on src/components/size-compare/Sizes.tsx
>    isSelfWrite?: boolean;
그리고 언니 말대로 SizeType을 수정하니까 오류가 좀 많아지네...
<img width="823" alt="image" src="https://user-images.githubusercontent.com/65955748/221126720-a56ef2e0-9793-4962-b4a5-fe95229206a0.png">

2023-02-24 09:51 UTC, leeseooo commented on src/components/size-compare/Sizes.tsx
>    isSelfWrite?: boolean;
나는 Sizes 컴포넌트 내부에서 이렇게 불러와서 사용하는 걸 말한거야!
```const productSizes = useRecoilValue(productSelfWriteState)```
그러면 props 넘길 필요도 없고, optional로 줘서 undefined 뜰 일도 없으니 괜찮지 않을까!

SizeType은 이렇게 고쳐봤어
```tsx
export interface SizeType {
  top: TopType;
  bottom: BottomType;
}
```
productSize 타입 에러는 이렇게 고쳐봤어 사실 단면 둘레 버튼은 무조건 눌려있으니까 default 값으로 true를 준다고 생각했어  
```tsx
isWidthOfBottom: productSelfWrite.isWidthOfBottom ?? true,
```

2023-02-24 11:14 UTC, ilmerry commented on src/components/size-compare/Sizes.tsx
>    isSelfWrite?: boolean;
응응 이해했어 근데 props로 전달해줘야하는 이유가 atom이랑 state가 타입이 달라서 변환해줘야 해서 저렇게 해준거였어
atom은 이런 형태야
```tsx
export const productSelfWriteState = atom<SizeTableType>({
  key: 'productSelfWriteSize',
  default: {
    size: '',
    topLength: null,
    shoulder: null,
    chest: null,
    isWidthOfTop: true,
    bottomLength: null,
    waist: null,
    thigh: null,
    rise: null,
    hem: null,
    isWidthOfBottom: true,
    topOrBottom: 0,
    userId: -99,
    topItemId: 0,
    bottomItemId: 0,
  },
});
``` 
productSizes를 optional로 줘서 다시 푸시 해봤는데 확인해줄래? 안될거같으면 언니가 말한 방식으로 바꿔볼게!

2023-02-25 09:27 UTC, leeseooo commented on src/components/size-compare/Sizes.tsx
>    isSelfWrite?: boolean;
은형아 브랜치 따와서 직접 해봤는데 참고해주라

먼저 `Sizes.tsx` 에서 productSizes props를 제거하고 RecoilValue를 불러왔어
상품 데이터를 전역상태로 저장하고 있는데 굳이 props로 넘길 필요가 없다고 생각해서 이렇게 작성했어. 

### 🔽Sizes.tsx - productSizes props 제거
```tsx
interface SizesProps {
  sizes: SizePropType;
  currentTab: TopOrBottom | null;
  isSelfWrite?: boolean;
}

function Sizes(props: SizesProps) {
  const { sizes, currentTab, isSelfWrite } = props;
  const productSize = useRecoilValue(productSelfWriteState);

  const calculateDifference = (key: keyof SizePropType, size: number) => {
    const compareTarget = productSize[key] as unknown as number;
    return size - compareTarget >= 0 ? `+${(size - compareTarget).toFixed(1)}` : (size - compareTarget).toFixed(1);
  };
```

### 🔽pages/size-compare.tsx - 회원가입 시 상의or하의 데이터를 입력하지 않고 넘어간 경우 처리
```tsx
  const isEmptyData = (data: object) => {
    return Object.values(data).every((value) => value === null);
  };
```
top 또는 bottom 데이터의 프로퍼티 값들이 null인지 체크하려고 만든 함수야
이걸 이용해서 상하의가 각각 null인지 체크하고 그에 맞는 뷰를 렌더링 해줬어.

### 🔽pages/size-compare.tsx -프로퍼티에 null값이 포함된 타입인 TopType과 BottomType 문제 해결하기
```tsx
 // 내 사이즈 조회
  useEffect(() => {
    (async () => {
      await getMySize();
      setIsLoading(false); // mySize recoil state가 도착하기 전 렌더링을 막기 위해 isLoading 생성
    })();
  }, []);

 if (isLoading) return <></>;

  const { top, bottom } = mySize;
  const { topLength, shoulder, chest } = top;
  const { bottomLength, waist, thigh, rise, hem } = bottom;
  const noSize = isEmptyData(top) && isEmptyData(bottom);

  const myTop: MyTopType = {
    topLength: topLength as number,
    shoulder: shoulder as number,
    chest: chest as number,
  };

  const myBottom: MyBottomType = {
    bottomLength: bottomLength as number,
    waist: waist as number,
    thigh: thigh as number,
    rise: rise as number,
    hem: hem as number,
  };
```
이 부분은 나도 더 나은 방법을 못 찾아서 타입 단언을 사용했어
`Sizes.tsx `컴포넌트에 null이 아닌 데이터를  보내주기 위해서 이렇게 작성했어.
기존의 TopType, BottomType은 number | null 타입이라서 `toFixed`메소드를 쓸 때 에러가 나더라고. null이 들어가지 않도록 MyTopType, MyBottomType은 프로퍼티들의 타입이 number로만 이루어지도록 만들었어.

### 🔽pages/size-compare.tsx - 수동입력일 때와 아닐 때 뷰 렌더링
```tsx
 const renderSelfWriteView = (
    <>
      {currentTab === 'top' ? (
        isEmptyData(top) ? (
          <Layout back close>
            <Main
              image={<Styled.Image src={icAlert} />}
              content={MESSAGE.NO_SIZE_COMPARE}
              caption={noSize}
              link={!noSize && getLink}
            />
          </Layout>
        ) : (
          <Layout title="내 사이즈와 이렇게 달라요" close>
            <SelfWriteCompare sizes={myTop} />
          </Layout>
        )
      ) : isEmptyData(bottom) ? (
        <Layout back close>
          <Main
            image={<Styled.Image src={icAlert} />}
            content={MESSAGE.NO_SIZE_COMPARE}
            caption={noSize}
            link={!noSize && getLink}
          />
        </Layout>
      ) : (
        <Layout title="내 사이즈와 이렇게 달라요" close>
          <SelfWriteCompare sizes={myBottom} />
        </Layout>
      )}
    </>
  );

  const renderCompareView = (
    <Layout back close>
      {!noSize && <Tabs currentTab={currentTab} handler={handleTab} />}
      {currentTab === 'top' ? (
        isEmptyData(top) ? (
          <>
            <Main
              image={<Styled.Image src={icAlert} />}
              content={MESSAGE.NO_SIZE_COMPARE}
              caption={noSize}
              link={!noSize && getLink}
            />
            {noSize && <SplitedButton />}
          </>
        ) : (
          <Compare sizes={myTop} currentTab={currentTab} />
        )
      ) : isEmptyData(bottom) ? (
        <>
          <Main
            image={<Styled.Image src={icAlert} />}
            content={MESSAGE.NO_SIZE_COMPARE}
            caption={noSize}
            link={!noSize && getLink}
          />
          {noSize && <SplitedButton />}
        </>
      ) : (
        <Compare sizes={myBottom} currentTab={currentTab} />
      )}
    </Layout>
  );

  return isSelfWrite ? renderSelfWriteView : renderCompareView;
}
```
이건 뷰를 편하게 렌더링 해보려고 JSX.Element로 분리했어. top 이나 bottom이 EmptyData라면(회원가입 시 데이터를 입력하지 않아 프로퍼티들이 null이라면) `비교가능한 사이즈가 없어요 뷰`를 보여줘야 해.

---
🔽 components/size-compare/index.tsx - SizePropType 타입 수정
```tsx
export type SizePropType = MyTopType | MyBottomType;

export interface MyTopType {
  topLength: number;
  shoulder: number;
  chest: number;
}
export interface MyBottomType {
  bottomLength: number;
  rise: number;
  waist: number;
  thigh: number;
  hem: number;
}
export interface TopType {
  topLength: number | null;
  shoulder: number | null;
  chest: number | null;
  isWidthOfTop: boolean | null;
}
export interface BottomType {
  bottomLength: number | null;
  rise: number | null;
  waist: number | null;
  thigh: number | null;
  hem: number | null;
  isWidthOfBottom: boolean | null;
}
```
SizePropType은 null이 없이 number로만 이루어진 프로퍼티를 갖게 바꿨어
일케 하면 Sizes에서 null처리를 안해줘도 돼

---
타입 에러는 이렇게 해결할 수 있을 것 같아. 근데 너가 해준대로 optional로 줘도 지금은, 상관은 없을 것 같아!
근데 type은 맞추면 되는거라 너무 타입에 구애받지 않고 작업했으면 좋겠어

한 가지 고민인건 우리가 전역상태를 많이 사용하고 있으니 props가 불필요하다는 생각이 들었어
릴리즈 이후에 다시 고민해보면서 전역상태에 모든걸 맡길지, 의존을 줄일지 논의해보자..

2023-02-25 09:29 UTC, leeseooo approved these changes

2023-02-25 12:54 UTC, merged